name: rumah_sehati_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  image_picker: 0.8.4+8
  flutter_screenutil: 5.2.0
  flutter_svg: 1.0.3
  get_storage: 2.0.3
  packages_info: 0.0.1-dev.1
  hive: 2.0.6
  hive_generator: 1.1.2
  hive_flutter: 1.1.0
  logger: 1.1.0
  firebase_core: 1.13.1
  firebase_crashlytics: 2.5.3
  intl: 0.17.0
  url_launcher: ^6.0.20
  flutter_share: ^2.0.0
  flutter_localizations: 
    sdk: flutter
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner: any
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
